services:
  nextjs:
    build: ./nextjs
    image: nextjs-image:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    networks:
      frontend-network:
        ipv4_address: 192.168.1.2
    healthcheck:
      test:
        ["CMD", "node", "-e", "require('http').get('http://localhost:3000')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  nginx:
    build: ./nginx
    image: nginx-image:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      nextjs:
        condition: service_healthy
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      frontend-network:
        ipv4_address: 192.168.1.3
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:443"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

networks:
  frontend-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
