services:
  nextjs:
    command: npm run dev
    volumes:
      - ./nextjs/app:/app
      - /app/node_modules
      - /app/.next

  backend:
    command: npm run dev
    volumes:
      - ./backend/app:/app
      - /app/node_modules
