apiVersion: v1
kind: Service
metadata:
  name: nextjs
  labels:
    app: nextjs
    project: technologie-chmurowe
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http-nextjs
      protocol: TCP
  selector:
    app: nextjs
