apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
    project: technologie-chmurowe
data:
  nginx.conf: |
    worker_processes 1; 

    events { 
        worker_connections 1024; 
    } 

    http { 
        include       /etc/nginx/mime.types; 
        default_type  application/octet-stream; 

        upstream nextjs_app { 
            server nextjs:3000; 
        } 
        upstream keycloak_server { 
            server keycloak:8080; 
        } 

        server { 
            listen 80; 
            server_name localhost; 

            access_log /var/log/nginx/redirect-localhost-access.log; 
            error_log /var/log/nginx/redirect-localhost-error.log debug; 

            return 301 https://$host$request_uri; 
        } 

        server { 
            listen 80; 
            server_name nginx; 

            access_log /var/log/nginx/internal-nginx-access.log; 
            error_log /var/log/nginx/internal-nginx-error.log debug; 

            location /auth/ { 
                proxy_pass http://keycloak_server/auth/; 
                proxy_set_header Host $http_host; 
                proxy_set_header X-Real-IP $remote_addr; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 

                proxy_set_header X-Forwarded-Proto https; 
                proxy_set_header X-Forwarded-Host localhost; 
                proxy_set_header X-Forwarded-Server localhost; 
                proxy_set_header X-Forwarded-Port 443; 

                proxy_http_version 1.1; 
                proxy_set_header Upgrade $http_upgrade; 
                proxy_set_header Connection "upgrade"; 
                proxy_read_timeout 900s; 
            } 

            location / { 
                return 403; 
            } 
        } 

        server { 
            listen 443 ssl; 
            server_name localhost; 

            access_log /var/log/nginx/external-localhost-ssl-access.log; 
            error_log /var/log/nginx/external-localhost-ssl-error.log debug; 

            ssl_certificate /etc/nginx/ssl/tls.crt; 
            ssl_certificate_key /etc/nginx/ssl/tls.key; 

            ssl_protocols TLSv1.2 TLSv1.3; 
            ssl_prefer_server_ciphers off; 
            ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384; 

            add_header X-Frame-Options "SAMEORIGIN" always; 
            add_header X-XSS-Protection "1; mode=block" always; 
            add_header X-Content-Type-Options "nosniff" always; 
            add_header Referrer-Policy "no-referrer-when-downgrade" always; 
            add_header Content-Security-Policy "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; object-src 'none'; frame-ancestors 'self';" always; 
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always; 

            location / { 
                proxy_pass http://nextjs_app; 
                proxy_http_version 1.1; 
                proxy_set_header Upgrade $http_upgrade; 
                proxy_set_header Connection "upgrade"; 
                proxy_set_header Host $host; 
                proxy_set_header X-Real-IP $remote_addr; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                proxy_set_header X-Forwarded-Proto $scheme; 
                proxy_set_header X-Forwarded-Host $host; 
                proxy_set_header X-Forwarded-Port $server_port; 
                proxy_cache_bypass $http_upgrade; 
            } 

            location /auth/ { 
                proxy_pass http://keycloak_server/auth/; 
                proxy_set_header Host $host; 
                proxy_set_header X-Real-IP $remote_addr; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                proxy_set_header X-Forwarded-Proto $scheme; 
                proxy_set_header X-Forwarded-Host $host; 
                proxy_set_header X-Forwarded-Server $host; 
                proxy_set_header X-Forwarded-Port $server_port; 

                proxy_http_version 1.1; 
                proxy_set_header Upgrade $http_upgrade; 
                proxy_set_header Connection "upgrade"; 
                proxy_read_timeout 900s; 
            } 
        } 
    }
