apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    project: technologie-chmurowe
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http-nginx
      protocol: TCP
    - name: http-internal
      port: 8080
      targetPort: http-internal
      protocol: TCP
  selector:
    app: nginx
