apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    project: technologie-chmurowe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        project: technologie-chmurowe
    spec:
      containers:
        - name: nginx
          image: szybkisum/nginx-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http-nginx
            - containerPort: 443
              name: https-nginx
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-ssl-volume
              mountPath: /etc/nginx/ssl
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: http-nginx
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http-nginx
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-ssl-volume
          secret:
            secretName: nginx-secrets
