apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
    project: technologie-chmurowe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        project: technologie-chmurowe
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.4
          imagePullPolicy: IfNotPresent
          args:
            - start-dev
            - --import-realm
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: management
          envFrom:
            - configMapRef:
                name: keycloak-config
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB_URL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KC_DB_URL_DATABASE
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KC_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KC_DB_PASSWORD
          volumeMounts:
            - name: keycloak-init-volume
              mountPath: /opt/keycloak/data/import/myrealm.json
              subPath: myrealm.json
              readOnly: true
          readinessProbe:
            httpGet:
              path: /auth/health/ready
              port: management
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /auth/health/live
              port: management
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      volumes:
        - name: keycloak-init-volume
          configMap:
            name: keycloak-init-configmap
            items:
              - key: myrealm.json
                path: myrealm.json
