apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak
    project: technologie-chmurowe
data:
  KEYCLOAK_ADMIN: "admin"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HOSTNAME_URL: "https://localhost/auth"
  KC_HTTP_RELATIVE_PATH: "/auth"
  KC_HTTP_ENABLED: "true"
  KC_PROXY_HEADERS: "xforwarded"
  KC_HEALTH_ENABLED: "true"
  KC_DB: "postgres"
  KC_DB_URL_HOST: "postgres"
  KC_DB_URL_PORT: "5432"
  KC_DB_SCHEMA: "public"
