# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: technologie-chmurowe-ingress
#   labels:
#     project: technologie-chmurowe
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
# spec:
#   ingressClassName: nginx
#   tls:
#     - hosts:
#         - localhost
#       secretName: nginx-secrets
#   rules:
#     - host: localhost
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: nginx
#                 port:
#                   number: 80
