apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    project: technologie-chmurowe
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres-port
      protocol: TCP
  selector:
    app: postgres
