apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
    project: technologie-chmurowe
type: Opaque
data:
  POSTGRES_DB: "ZGF0YWJhc2U="
  POSTGRES_USER: "dXNlcg=="
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="
